easy_admin:
   entities:
       # List the entity class name you want to manage
       - App\Entity\Category
       - App\Entity\User
       - App\Entity\Commentary
       - App\Entity\Places
       - App\Entity\PlacePicture
       - App\Entity\CommentaryPicture
       
       
